config/routes.rb
Rails.application.routes.draw do
  devise_for :photographers

  root to: 'photographers#show'

  get('/levels/new', { :controller => 'levels', :action => 'new' })
  get('/create_level', { :controller => 'levels', :action => 'create' })

  get('/levels', { :controller => 'levels', :action => 'index' })
  get('/levels/:id', { :controller => 'levels', :action => 'show' })

  get('/levels/:id/edit', { :controller => 'levels', :action => 'edit' })
  get('/update_level/:id', { :controller => 'levels', :action => 'update' })

  get('/delete_level/:id', { :controller => 'levels', :action => 'destroy' })

  get('/event_titles/new', { :controller => 'event_titles', :action => 'new' })
  get('/create_event_title', { :controller => 'event_titles', :action => 'create' })

  get('/event_titles', { :controller => 'event_titles', :action => 'index' })
  get('/event_titles/:id', { :controller => 'event_titles', :action => 'show' })

  get('/event_titles/:id/edit', { :controller => 'event_titles', :action => 'edit' })
  get('/update_event_title/:id', { :controller => 'event_titles', :action => 'update' })

  get('/delete_event_title/:id', { :controller => 'event_titles', :action => 'destroy' })

  get('/schools/new', { :controller => 'schools', :action => 'new' })
  get('/create_school', { :controller => 'schools', :action => 'create' })

  get('/schools', { :controller => 'schools', :action => 'index' })
  get('/schools/:id', { :controller => 'schools', :action => 'show' })

  get('/schools/:id/edit', { :controller => 'schools', :action => 'edit' })
  get('/update_school/:id', { :controller => 'schools', :action => 'update' })

  get('/delete_school/:id', { :controller => 'schools', :action => 'destroy' })

  get('/genders/new', { :controller => 'genders', :action => 'new' })
  get('/create_gender', { :controller => 'genders', :action => 'create' })

  get('/genders', { :controller => 'genders', :action => 'index' })
  get('/genders/:id', { :controller => 'genders', :action => 'show' })

  get('/genders/:id/edit', { :controller => 'genders', :action => 'edit' })
  get('/update_gender/:id', { :controller => 'genders', :action => 'update' })

  get('/delete_gender/:id', { :controller => 'genders', :action => 'destroy' })

  get('/sports/new', { :controller => 'sports', :action => 'new' })
  get('/create_sport', { :controller => 'sports', :action => 'create' })

  get('/sports', { :controller => 'sports', :action => 'index' })
  get('/sports/:id', { :controller => 'sports', :action => 'show' })

  get('/sports/:id/edit', { :controller => 'sports', :action => 'edit' })
  get('/update_sport/:id', { :controller => 'sports', :action => 'update' })

  get('/delete_sport/:id', { :controller => 'sports', :action => 'destroy' })

  get('/locations/new', { :controller => 'locations', :action => 'new' })
  get('/create_location', { :controller => 'locations', :action => 'create' })

  get('/locations', { :controller => 'locations', :action => 'index' })
  get('/locations/:id', { :controller => 'locations', :action => 'show' })

  get('/locations/:id/edit', { :controller => 'locations', :action => 'edit' })
  get('/update_location/:id', { :controller => 'locations', :action => 'update' })

  get('/delete_location/:id', { :controller => 'locations', :action => 'destroy' })

  get('/photographers/new', { :controller => 'photographers', :action => 'new' })
  get('/create_photographer', { :controller => 'photographers', :action => 'create' })

  get('/photographers', { :controller => 'photographers', :action => 'index' })
  get('/photographers/:id', { :controller => 'photographers', :action => 'show' })

  get('/photographers/:id/edit', { :controller => 'photographers', :action => 'edit' })
  get('/update_photographer/:id', { :controller => 'photographers', :action => 'update' })

  get('/delete_photographer/:id', { :controller => 'photographers', :action => 'destroy' })

  get('/games/new', { :controller => 'games', :action => 'new' })
  get('/create_game', { :controller => 'games', :action => 'create' })

  get('/games', { :controller => 'games', :action => 'index' })
  get('/games/:id', { :controller => 'games', :action => 'show' })

  get('/games/:id/edit', { :controller => 'games', :action => 'edit' })
  get('/update_game/:id', { :controller => 'games', :action => 'update' })

  get('/delete_game/:id', { :controller => 'games', :action => 'destroy' })

  get('/game_check_in/:id', { :controller => 'games', :action => 'check_in' })

  get('/game_check_out/:id', { :controller => 'games', :action => 'check_out' })

  get('/game_rainout/:id', { :controller => 'games', :action => 'rainout' })

  get('/game_denied_entry/:id', { :controller => 'games', :action => 'denied_entry' })

  get('/game_equipment_failure/:id', { :controller => 'games', :action => 'equipment_failure' })

  get('/game_comment/:id', { :controller => 'games', :action => 'comment' })

  get('/manage_attributes', { :controller => 'attributes', :action => 'manage'})

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Varsity Views</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/superhero/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/photographers/<%= current_photographer.try(:id) %>" class="navbar-brand">Varsity Views Photographer Tool</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if current_photographer == nil %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/photographers/sign_up">Sign up</a></li>
          <li><a href="/photographers/sign_in">Sign in</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->

    <% else %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a>Welcome, <%= current_photographer.first_name %> <%= current_photographer.last_name %>!</a></li>
          <li><a href="/photographers/<%=current_photographer.id%>">View My Games</a></li>
          <li><a href="/photographers/<%=current_photographer.id%>/edit ">Edit My Profile</a></li>

          <% if current_photographer.admin_status == 'true' %>

            <li><a href="/games/">View All Games</a></li>
            <li><a href="/manage_attributes">Manage Game Attributes</a></li>
          <% else %>
          <% end %>

        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_photographer != nil %>
            <li><a href="/photographers/edit">Change your Password</a></li>
            <li><a href="/photographers/sign_out" data-method="delete">Sign out</a></li>
          <% else %>
            <li><a href="/photographers/sign_up">Sign up</a></li>
            <li><a href="/photographers/sign_in">Sign in</a></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->

    <% end %>

  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>